//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseOperation
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblbatch_schedule_attendance
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblbatch_schedule_attendance()
        {
            this.tblschedule_attendance = new HashSet<tblschedule_attendance>();
        }
    
        public int schedule_attendance_id { get; set; }
        public Nullable<int> batch_schedule_id { get; set; }
        public Nullable<System.DateTime> attendance_date { get; set; }
    
        public virtual tblbatch_schedule tblbatch_schedule { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblschedule_attendance> tblschedule_attendance { get; set; }
    }
}
