//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseOperation
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblbatch
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblbatch()
        {
            this.tblbatch_schedule = new HashSet<tblbatch_schedule>();
            this.tblbatch_students = new HashSet<tblbatch_students>();
        }
    
        public int batch_id { get; set; }
        public string batch_name { get; set; }
        public Nullable<int> topic_id { get; set; }
        public Nullable<int> trainer_id { get; set; }
        public Nullable<System.DateTime> start_date { get; set; }
        public Nullable<System.DateTime> end_date { get; set; }
        public string batch_time { get; set; }
        public string status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblbatch_schedule> tblbatch_schedule { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblbatch_students> tblbatch_students { get; set; }
        public virtual tbltraining_topics tbltraining_topics { get; set; }
        public virtual tbltrainer tbltrainer { get; set; }
    }
}
