//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseOperation
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblbatch_schedule
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblbatch_schedule()
        {
            this.tblbatch_schedule_attendance = new HashSet<tblbatch_schedule_attendance>();
        }
    
        public int batch_schedule_id { get; set; }
        public Nullable<int> batch_id { get; set; }
        public Nullable<int> content_id { get; set; }
        public Nullable<System.DateTime> expected_date { get; set; }
        public Nullable<System.DateTime> actual_date { get; set; }
    
        public virtual tbltopic_contents tbltopic_contents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblbatch_schedule_attendance> tblbatch_schedule_attendance { get; set; }
        public virtual tblbatch tblbatch { get; set; }
    }
}
