//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseOperation
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblcourse_topics
    {
        public int course_topics { get; set; }
        public Nullable<int> course_id { get; set; }
        public Nullable<int> topic_id { get; set; }
    
        public virtual tbltraining_courses tbltraining_courses { get; set; }
        public virtual tbltraining_topics tbltraining_topics { get; set; }
        public List<TopicModel> topicModels { get; set; }
    }

    public class TopicModel
    {
        public int topic_id { get; set; }
        public string topic_name { get; set; }
        public bool isSeletcted { get; set; }
    }

}
