//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseOperation
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblschedule_attendance
    {
        public int attendance_id { get; set; }
        public Nullable<int> schedule_attendance_id { get; set; }
        public Nullable<int> registration_id { get; set; }
        public Nullable<int> is_present { get; set; }
    
        public virtual tblbatch_schedule_attendance tblbatch_schedule_attendance { get; set; }
        public virtual tblstudent_registrations tblstudent_registrations { get; set; }
    }
}
