//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseOperation
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblstudent_details
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblstudent_details()
        {
            this.tblstudent_registrations = new HashSet<tblstudent_registrations>();
        }
    
        public int student_id { get; set; }
        public string student_name { get; set; }
        public string gender { get; set; }
        public string mobile_number { get; set; }
        public string email_address { get; set; }
        public string password { get; set; }
        public Nullable<System.DateTime> birth_date { get; set; }
        public string profile_photo { get; set; }
        public string qualification { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblstudent_registrations> tblstudent_registrations { get; set; }
    }
}
