//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseOperation
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblstudent_payments
    {
        public int payment_id { get; set; }
        public Nullable<int> registration_id { get; set; }
        public Nullable<System.DateTime> payment_date { get; set; }
        public Nullable<double> payment_amount { get; set; }
        public string payment_mode { get; set; }
        public string payment_description { get; set; }
    
        public virtual tblstudent_registrations tblstudent_registrations { get; set; }
    }
}
