//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseOperation
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbltraining_course_fees
    {
        public int fee_id { get; set; }
        public Nullable<int> course_id { get; set; }
        public double fees_amount { get; set; }
        public Nullable<double> gst { get; set; }
        public string fee_mode { get; set; }
    
        public virtual tbltraining_courses tbltraining_courses { get; set; }
    }
}
