//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseOperation
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbltrainer_topics
    {
        public int trainer_topic_id { get; set; }
        public Nullable<int> topic_id { get; set; }
        public Nullable<int> trainer_id { get; set; }
    
        public virtual tbltraining_topics tbltraining_topics { get; set; }
        public virtual tbltrainer tbltrainer { get; set; }
    }
}
