//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseOperation
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbltopic_contents
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbltopic_contents()
        {
            this.tblbatch_schedule = new HashSet<tblbatch_schedule>();
        }
    
        public int content_id { get; set; }
        public Nullable<int> topic_id { get; set; }
        public string content_name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblbatch_schedule> tblbatch_schedule { get; set; }
        public virtual tbltraining_topics tbltraining_topics { get; set; }
    }
}
